import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {OrbitControls,Line,ContactShadows} from '@react-three/drei';
import {Suspense,useMemo,useRef,useEffect} from 'react';
import * as THREE from 'three';
const defaultNodes:Record<string,[number,number]>={W:[-80,0],J1:[0,0],J2:[80,0],J3:[160,0],J4:[0,80],J5:[80,80],J6:[160,80],J7:[80,-80],J8:[240,-80],E:[240,80]};
const defaultPairs=[['W','J1'],['J1','J2'],['J2','J3'],['J1','J4'],['J2','J5'],['J3','J6'],['J4','J5'],['J5','J6'],['J6','E'],['J2','J7'],['J7','J8'],['J3','J8'],['J8','E']];
const xyz=(p:number[],height=0):[number,number,number]=>[p[0]-80,height,-p[1]];
const palette=['#8b9eaa','#8c9995','#a49c8c','#6f8a99'];
function Label({text,position,color='#b6cddd',background='#112236',onClick}:{text:string;position:[number,number,number];color?:string;background?:string;onClick?:()=>void}){
 const texture=useMemo(()=>{const c=document.createElement('canvas');c.width=640;c.height=128;const ctx=c.getContext('2d')!;ctx.fillStyle=background;ctx.beginPath();ctx.roundRect(3,3,634,122,16);ctx.fill();ctx.strokeStyle=color;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle=color;ctx.font=`500 ${Math.min(66,Math.floor(570/(text.length*.57)))}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,320,65);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t},[text,color,background]);
 useEffect(()=>()=>texture.dispose(),[texture]);
 return <sprite position={position} scale={[text.length>14?.23:.17,text.length>14?.046:.034,1]} renderOrder={50} onClick={e=>{e.stopPropagation();onClick?.()}}><spriteMaterial map={texture} depthTest={false} sizeAttenuation={false} transparent/></sprite>
}
function Buildings({nodes,pairs}:{nodes:Record<string,number[]>;pairs:string[][]}){
 const blocks=useMemo(()=>{const result:any[]=[];let n=0;for(let x=-60;x<=200;x+=22)for(let z=-125;z<=135;z+=23){if(pairs.some(([a,b])=>{const [ax,az]=nodes[a],[bx,bz]=nodes[b];const t=Math.max(0,Math.min(1,((x-ax)*(bx-ax)+(z-az)*(bz-az))/((bx-ax)**2+(bz-az)**2)));return Math.hypot(x-ax-t*(bx-ax),z-az-t*(bz-az))<23}))continue;const h=8+((n*17)%28);result.push({x,z,h,n:n++});}return result},[nodes,pairs]);
 return <group>{blocks.map(b=><group key={b.n} position={xyz([b.x,b.z])}><mesh castShadow position={[0,b.h/2,0]}><boxGeometry args={[14,b.h,15]}/><meshStandardMaterial color={palette[b.n%4]} roughness={.75}/></mesh><mesh position={[0,b.h+.2,0]}><boxGeometry args={[14.3,.5,15.3]}/><meshStandardMaterial color="#50667b"/></mesh>{Array.from({length:Math.floor(b.h/5)},(_,i)=><mesh key={i} position={[0,4+i*5,7.55]}><boxGeometry args={[11,.65,.12]}/><meshStandardMaterial color={b.n%4===0?'#b2b0a0':'#599cb7'} emissive={b.n%4===0?'#817b58':'#306b89'} emissiveIntensity={.4}/></mesh>)}</group>)}</group>
}
function Streetscape({nodes,pairs}:{nodes:Record<string,number[]>;pairs:string[][]}){
 const trees=useMemo(()=>pairs.flatMap(([a,b])=>{const p=nodes[a],q=nodes[b],dx=q[0]-p[0],dy=q[1]-p[1],length=Math.hypot(dx,dy);return Array.from({length:Math.max(0,Math.floor(length/24)-1)},(_,i)=>{const t=(i+1)/Math.floor(length/24);return [p[0]+dx*t-dy/length*12,p[1]+dy*t+dx/length*12]})}),[nodes,pairs]);
 return <group>{trees.map((p,i)=><group key={i} position={xyz(p)}><mesh position={[0,2,0]}><cylinderGeometry args={[.4,.6,4,5]}/><meshStandardMaterial color="#5e5145"/></mesh><mesh castShadow position={[0,6,0]}><icosahedronGeometry args={[3.3,1]}/><meshStandardMaterial color={i%2?'#32675d':'#45795c'} roughness={1}/></mesh></group>)}<group position={xyz([nodes.E[0]+15,nodes.E[1]+30])}><mesh castShadow position={[0,12,0]}><boxGeometry args={[30,24,20]}/><meshStandardMaterial color="#9cb5be"/></mesh><mesh position={[0,24.5,0]}><boxGeometry args={[32,1,22]}/><meshStandardMaterial color="#34526a"/></mesh>{[5,11,17].map(y=><mesh key={y} position={[0,y,10.1]}><boxGeometry args={[25,2.2,.2]}/><meshStandardMaterial color="#427b94" emissive="#286a82" emissiveIntensity={.5}/></mesh>)}<mesh position={[0,27,0]}><boxGeometry args={[4,1,1]}/><meshBasicMaterial color="#7be4d0"/></mesh><mesh position={[0,27,0]}><boxGeometry args={[1,1,4]}/><meshBasicMaterial color="#7be4d0"/></mesh></group></group>
}
function Road({a,b}:{a:number[];b:number[]}){const dx=b[0]-a[0],dy=b[1]-a[1],length=Math.hypot(dx,dy);return <group position={xyz([(a[0]+b[0])/2,(a[1]+b[1])/2],.05)} rotation={[0,Math.atan2(dy,dx),0]}><mesh receiveShadow><boxGeometry args={[length,0.3,14]}/><meshStandardMaterial color="#243042"/></mesh>{[-7.3,7.3].map(z=><mesh key={z} position={[0,.1,z]}><boxGeometry args={[length,.25,.65]}/><meshStandardMaterial color="#6c8090"/></mesh>)}{Array.from({length:Math.floor(length/10)},(_,i)=><mesh key={i} position={[-length/2+i*10+5,.23,0]}><boxGeometry args={[4,.05,.2]}/><meshBasicMaterial color="#728093"/></mesh>)}</group>}
function Car({v,frozen,reduced}:{v:any;frozen:boolean;reduced:boolean}){
 const ref=useRef<THREE.Group>(null);const lamp=useRef<THREE.Mesh>(null);const initial=useMemo(()=>xyz([v.x,v.y],.8),[]);const ambulance=v.id==='ambulance';
 useFrame(({clock},dt)=>{if(ref.current){const target=new THREE.Vector3(...xyz([v.x,v.y],.8));if(frozen||reduced)ref.current.position.copy(target);else ref.current.position.lerp(target,1-Math.exp(-dt*12));const delta=Math.atan2(Math.sin(v.angle-ref.current.rotation.y),Math.cos(v.angle-ref.current.rotation.y));ref.current.rotation.y+=delta*(frozen||reduced?1:1-Math.exp(-dt*12));}
 if(lamp.current)(lamp.current.material as THREE.MeshStandardMaterial).emissiveIntensity=frozen||reduced?1:clock.elapsedTime%0.8<.4?3:.3});
 return <group ref={ref} position={initial} rotation={[0,v.angle,0]}><mesh castShadow position={[0,ambulance?1.4:.6,0]}><boxGeometry args={[ambulance?6:4,ambulance?2.8:1.3,2.2]}/><meshStandardMaterial color={ambulance?'#f6f7f9':Number(v.id.replace(/\D/g,''))%2?'#f2b671':'#74b8c8'} metalness={.15} roughness={.4}/></mesh><mesh position={[ambulance?1.8:.7,ambulance?2.2:1.5,0]}><boxGeometry args={[1.4,.65,2.05]}/><meshStandardMaterial color="#123149" metalness={.6}/></mesh>{ambulance&&<><mesh ref={lamp} position={[0,3,0]}><boxGeometry args={[1.4,.4,1.7]}/><meshStandardMaterial color="#438bff" emissive="#236dff" emissiveIntensity={3}/></mesh><mesh position={[0,1.4,1.12]}><boxGeometry args={[1.7,.45,.04]}/><meshBasicMaterial color="#ef534e"/></mesh><mesh position={[0,1.4,1.13]}><boxGeometry args={[.45,1.7,.04]}/><meshBasicMaterial color="#ef534e"/></mesh><Label position={[0,9,0]} text="A1 - SIMULATED" color="#dceeff" background="#265cb2"/></>}{[-1.6,1.6].flatMap(x=>[-1.15,1.15].map(z=><mesh key={`${x}-${z}`} position={[x,.2,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.55,.55,.35,12]}/><meshStandardMaterial color="#101620"/></mesh>))}</group>
}
function Signal({c,selected,onSelect,nodes}:{c:any;selected:string;onSelect:(v:string)=>void;nodes:Record<string,number[]>}){const pos=nodes[c.id];const color=c.phase==='GREEN'?'#48edbd':c.phase==='YELLOW'?'#ffbc5a':'#fa6b73';return <group position={xyz(pos)}><mesh position={[0,.27,0]} onClick={()=>onSelect(c.id)}><boxGeometry args={[15,.3,15]}/><meshStandardMaterial color={selected===c.id?'#344d62':'#29374a'}/></mesh><mesh position={[8,3.5,8]}><cylinderGeometry args={[.25,.25,7,8]}/><meshStandardMaterial color="#6f8193"/></mesh><mesh position={[8,7.5,8]}><boxGeometry args={[1.4,3.2,1.1]}/><meshStandardMaterial color="#111722"/></mesh><mesh position={[8,7.5,8.6]}><sphereGeometry args={[.42,12,12]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={2}/></mesh><Label position={[0,13,0]} text={`${c.id}  ·  E${c.generation}`} color={!c.readback||!c.online||!c.writable?'#ff9393':selected===c.id?'#69e2ba':'#b6cddd'} onClick={()=>onSelect(c.id)}/></group>}
function Camera({follow,vehicle,reset,top,reduced}:{follow:boolean;vehicle:any;reset:number;top:boolean;reduced:boolean}){
 const controls=useRef<any>(null);const {camera}=useThree();const prev=useRef(reset);const prevTop=useRef(top);
 useFrame((_,dt)=>{if(prev.current!==reset||prevTop.current!==top){camera.position.set(...(top?[0,420,.1]:[250,270,290]) as [number,number,number]);controls.current?.target.set(0,0,0);prev.current=reset;prevTop.current=top;controls.current?.update()}
 if(follow&&vehicle&&controls.current){const p=new THREE.Vector3(...xyz([vehicle.x,vehicle.y]));controls.current.target.lerp(p,reduced?1:Math.min(dt*3,1));camera.position.lerp(p.clone().add(new THREE.Vector3(55,65,70)),reduced?1:Math.min(dt*2,1));controls.current.update();}});
 return <OrbitControls ref={controls} enableDamping={!reduced} minDistance={35} maxDistance={500} maxPolarAngle={Math.PI/2.12} enablePan={!follow}/>;
}
export default function City({state,selected,onSelect,follow,reset,frozen=false,reduced=false,top=false,preview}:{state:any;selected:string;onSelect:(v:string)=>void;follow:boolean;reset:number;frozen?:boolean;reduced?:boolean;top?:boolean;preview?:string[]}){
 const nodes:Record<string,number[]>=useMemo(()=>state?.nodes||defaultNodes,[state?.id]);const pairs:string[][]=useMemo(()=>state?.pairs||defaultPairs,[state?.id]);
 const route=state?.route||['W','J1','J2','J3','J6','E'];const proposed=state?.recovery?.successor;const controllers=state?.controllers||Object.keys(nodes).filter(n=>n.startsWith('J')).map(id=>({id,phase:'RED',generation:1,readback:true,online:true,writable:true}));
 return <Canvas shadows camera={{position:[250,270,290],fov:43}} dpr={[1,1.5]} gl={{antialias:true}}><color attach="background" args={['#152638']}/><fog attach="fog" args={['#152638',600,1100]}/><ambientLight intensity={1.8}/><hemisphereLight args={['#c7e7ff','#273042',1.5]}/><directionalLight position={[70,180,90]} intensity={2.9} color="#ffe3bc" castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-220} shadow-camera-right={220} shadow-camera-top={170} shadow-camera-bottom={-170}/><Suspense fallback={null}><mesh rotation={[-Math.PI/2,0,0]} position={[0,-.4,0]} receiveShadow><planeGeometry args={[650,500]}/><meshStandardMaterial color="#152537"/></mesh><gridHelper args={[640,64,'#23394d','#1c3042']} position={[0,-.1,0]}/>{pairs.map(([a,b])=><Road key={a+b} a={nodes[a]} b={nodes[b]}/>)}<Buildings nodes={nodes} pairs={pairs}/><Streetscape nodes={nodes} pairs={pairs}/><Line points={route.map((n:string)=>xyz(nodes[n],.8))} color="#6fb7f4" lineWidth={3} transparent opacity={.8}/>{state?.segment>0&&<Line points={route.slice(0,state.segment+1).map((n:string)=>xyz(nodes[n],1.2))} color="#92a7c2" lineWidth={4}/>}<IncidentMarkers incidents={state?.incidents||[]} nodes={nodes}/>{proposed&&state.status==='RECOVERING'&&<Line points={proposed.map((n:string)=>xyz(nodes[n],1))} color="#ffce7a" lineWidth={4} dashed dashSize={3} gapSize={2}/>} {preview&&preview.length>1&&<Line points={preview.map((n:string)=>xyz(nodes[n],1.8))} color="#9d93ff" lineWidth={5} dashed dashSize={4} gapSize={2}/>} {controllers.map((c:any)=><Signal key={c.id} nodes={nodes} c={c} selected={selected} onSelect={onSelect}/>)}{(state?.vehicles||[]).map((v:any)=><Car key={v.id} v={v} frozen={frozen} reduced={reduced}/>)}<Label position={xyz(nodes.W,5)} text="DISPATCH"/><Label position={xyz(nodes.E,5)} text="+ CENTRAL HOSPITAL" color="#7ee9c2"/><ContactShadows opacity={.25} scale={500} blur={2} far={60}/></Suspense><Camera top={top} reduced={reduced} follow={follow} vehicle={state?.vehicles?.find((v:any)=>v.id==='ambulance')} reset={reset}/></Canvas>
}

function IncidentMarkers({incidents,nodes}:{incidents:any[];nodes:Record<string,number[]>}){
 return <>{incidents.filter(i=>i.status==='ACTIVE'&&i.edge).map(i=>{const a=nodes[i.edge[0]],b=nodes[i.edge[1]];const p=[a[0]+(b[0]-a[0])*i.position,a[1]+(b[1]-a[1])*i.position];const color=i.kind==='congestion'?'#ffbe60':'#ff635f';return <group key={i.id}><Line points={[xyz(a,1.7),xyz(b,1.7)]} color={color} lineWidth={7} transparent opacity={.7}/><group position={xyz(p,3)}><mesh><coneGeometry args={[3,6,4]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={.5}/></mesh><Label position={[0,11,0]} text={`${i.kind.toUpperCase()} ${i.edge.join(' > ')}`} color={color}/></group></group>})}</>
}
