import {Component,lazy,Suspense,useState,type ReactNode} from 'react';
import {Activity,Ambulance,ArrowRight,Check,Clock,Focus,GitBranch,Hospital,Layers,MapPin,Maximize2,RotateCcw,ShieldCheck,TriangleAlert,Waypoints,Zap} from 'lucide-react';
import {IncidentPanel} from './Incidents';
const City=lazy(()=>import('./City'));
type Props={state:any;frozen:boolean;reduced:boolean;disabled:boolean;selected:string;onSelect:(id:string)=>void;onNavigate:(tab:string)=>void;onAdd:()=>void;action:(path:string,body?:any)=>Promise<any>};
const value=(n:number|null|undefined,unit='')=>n==null?'Unavailable':`${Number(n.toFixed(1))}${unit}`;

class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{
 state={failed:false};
 static getDerivedStateFromError(){return {failed:true}}
 render(){return this.state.failed?<div className="scene-unavailable"><Layers size={32}/><h3>3D view unavailable</h3><p>Enable browser hardware acceleration and reload. Mission data and controls remain available.</p></div>:this.props.children}
}

export function SceneView({state,frozen=false,reduced=false,selected='J3',onSelect=()=>{},preview,compact=false}:{state:any;frozen?:boolean;reduced?:boolean;selected?:string;onSelect?:(id:string)=>void;preview?:string[];compact?:boolean}){
 const [follow,setFollow]=useState(false),[reset,setReset]=useState(0),[top,setTop]=useState(false);
 return <div className={`world-view ${compact?'compact':''}`}><SceneBoundary><Suspense fallback={<div className="scene-unavailable"><Layers size={28}/><p>Preparing the 3D city…</p></div>}><City state={state} selected={selected} onSelect={onSelect} follow={follow} reset={reset} frozen={frozen} reduced={reduced} top={top} preview={preview}/></Suspense></SceneBoundary>
  <div className="world-caption"><span className="source-pill"><i/>{state?'SIMULATED TELEMETRY':'NETWORK PREVIEW'}</span><span>{value(state?.time,' s')}</span></div>
  <div className="world-tools"><button aria-label="Reset camera" title="Reset camera" onClick={()=>{setFollow(false);setTop(false);setReset(v=>v+1)}}><RotateCcw size={16}/></button><button aria-label="Follow ambulance" title="Follow ambulance" aria-pressed={follow} onClick={()=>{setTop(false);setFollow(!follow)}}><Focus size={17}/></button><button aria-label="Top-down view" title="Top-down view" aria-pressed={top} onClick={()=>{setFollow(false);setTop(!top)}}><Maximize2 size={17}/></button></div>
  <div className="world-legend"><span><i className="route-key"/>Current route</span><span><i className="route-key proposed"/>Proposed</span><span><i className="route-key blocked"/>Incident</span></div>
  {preview&&<span className="preview-label">Alternative preview · not activated</span>}
 </div>
}

export function MissionRail({state,onNavigate}:{state:any;onNavigate:(tab:string)=>void}){
 const pending=state?.status==='RECOVERING'?(state.recovery?.candidates||[]).filter((n:string)=>!state.controllers.some((c:any)=>c.id===n&&c.generation===state.recovery.generation&&c.mode==='COMMITTED')):[];
 return <aside className="mission-rail"><div className="rail-heading">MISSION CONTROL <span>01</span></div><div className="vehicle-emblem"><Ambulance size={32}/><span>A1</span></div><span className="eyebrow">EMERGENCY RESPONSE</span><h2>Ambulance A1</h2><p className="rail-destination"><MapPin size={14}/> Central Hospital</p><span className={`status-tag ${state?.status==='FALLBACK'?'bad':''}`}>{state?.status||'AWAITING DATA'}</span><div className="rail-facts"><div><span>Remaining ETA</span><b>{value(state?.eta,' s')}</b></div><div><span>Speed</span><b>{value(state?.ambulance_speed,' km/h')}</b></div><div><span>Recoveries</span><b>{state?.metrics?.recovery_count??'—'}</b></div></div><button className="button secondary full" onClick={()=>onNavigate('missions')}>Mission details <ArrowRight size={14}/></button><div className="rail-callout"><ShieldCheck size={18}/><strong>{pending.length?'Verification pending':state?.status==='FALLBACK'?'Replacement unavailable':'Evidence-led recovery'}</strong><p>{pending.length?`Waiting for ${pending.join(', ')}.`:state?.decision?.reason||'Controller verification remains separate from route availability.'}</p></div><div className="rail-source">SIMULATION MODE<p>One emergency vehicle. Hospital acceptance is not connected.</p></div></aside>
}

function Facts({items}:{items:[string,ReactNode][]}){return <dl className="detail-facts">{items.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>}
function RouteChain({route}:{route:string[]}){return <div className="route-chain">{route.map((n,i)=><span key={`${n}-${i}`}><b>{n}</b>{i<route.length-1&&<ArrowRight size={13}/>}</span>)}</div>}
export function EventTimeline({events}:{events:any[]}){return <div className="journey-timeline">{events.length?events.slice(-7).map(e=><div className={`timeline-node ${e.kind==='FAULT'?'fault':''}`} key={e.id}><span className="timeline-dot">{e.kind==='FAULT'?<Zap size={12}/>:<Check size={12}/>}</span><small>{value(e.time,' s')}</small><b>{e.title}</b></div>):<div className="quiet-empty"><Clock size={18}/> Start a journey to record its timeline.</div>}</div>}

export function Readiness({state}:{state:any}){
 const nodes=state?.recovery?.candidates||state?.route?.slice((state?.segment||0)+1).filter((n:string)=>n.startsWith('J'))||[];
 return <div className="readiness-row">{nodes.map((n:string)=>{const c=state.controllers.find((v:any)=>v.id===n);const fault=!c?.online||!c?.readback||!c?.writable;const verified=state.recovery&&c?.generation===state.recovery.generation&&['ACTIVE','COMMITTED'].includes(c?.mode);return <div key={n} className={fault?'unavailable':verified?'verified':'pending'}><span>{fault?<TriangleAlert size={15}/>:verified?<ShieldCheck size={15}/>:<Clock size={15}/>}</span><b>{n}</b><small>{fault?'Unavailable':verified?'Verified':'Unverified'}</small></div>})}{!nodes.length&&<p className="empty-inline">No downstream signal obligations.</p>}</div>
}

export function Operations(props:Props&{tab:string}){
 const {tab,state:s,onNavigate,onAdd,selected,onSelect,disabled,action,frozen,reduced}=props;
 const [candidate,setCandidate]=useState(-1),[filter,setFilter]=useState('ALL');
 if(!s)return <section className="panel waiting-panel"><Activity size={36}/><h2>Waiting for simulation data</h2><p>Start the research service to connect these views.</p></section>;
 const common={state:s,selected,onSelect,frozen,reduced};
 const active=(s.incidents||[]).filter((i:any)=>i.status==='ACTIVE');
 if(tab==='missions')return <>
  <section className="mission-banner"><div className="vehicle-emblem"><Ambulance size={32}/></div><div><span className="eyebrow">CURRENT MISSION · A1</span><h2>Every turn, accounted for.</h2><p>Dispatch → Central Hospital · {s.mode}</p></div><span className="status-tag">{s.status}</span></section>
  <div className="operation-grid"><section className="panel"><div className="panel-title">Journey overview <span className="tag">SIMULATED</span></div><SceneView {...common}/><div className="panel-pad"><RouteChain route={s.route}/></div></section><section className="panel panel-pad"><span className="eyebrow">MISSION BRIEF</span><h2>Ambulance A1</h2><Facts items={[["Destination","Central Hospital"],["Hospital acceptance",'Not connected'],['Position source',s.mode],['Remaining ETA',value(s.eta,' s')],['Elapsed',value(s.time,' s')],['Recovery strategy',s.strategy==='partial'?'Partial verified recovery':'Whole-network baseline'],['Recorded transfers',s.metrics.recovery_count||0]]}/><button className="button primary full" onClick={()=>onNavigate('live')}>Open Command Centre <ArrowRight size={16}/></button><button className="button secondary full spaced" onClick={()=>onNavigate('scenarios')}>Configure next journey</button></section></div>
  <section className="panel spaced"><div className="panel-title">Journey timeline <span className="subtle">Backend events</span></div><EventTimeline events={s.events||[]}/></section>
 </>;
 if(tab==='routes'){
  const options=s.alternatives||[],chosen=options[candidate];
  return <><div className="operation-grid route-layout"><section className="panel"><div className="panel-title"><span>Corridor geography</span><button className="button small secondary" onClick={()=>setCandidate(-1)}>Current route</button></div><SceneView {...common} preview={chosen?.route}/><div className="panel-pad"><RouteChain route={chosen?.route||s.route}/></div></section><section className="panel panel-pad"><span className="eyebrow">PLANNER DECISION</span><h2>{s.status==='FALLBACK'?'No verified replacement':'A route with a reason.'}</h2><p className="body-copy">{s.decision?.reason||'Original corridor selected. Add an incident to evaluate alternatives.'}</p><div className="notice-box"><ShieldCheck size={20}/><p>A feasible road route does not guarantee signal priority. Local verification is required before a replacement is activated.</p></div><button className="button secondary full" disabled={disabled} onClick={onAdd}>Introduce a disruption <Zap size={15}/></button></section></div><div className="candidate-grid">{options.length?options.map((o:any,i:number)=><button className={`candidate-card ${candidate===i?'selected':''}`} key={i} onClick={()=>setCandidate(i)}><div><span className="candidate-number">0{i+1}</span><span className="tag">{o.labels?.join(' · ')||'Alternative'}</span></div><h3>{value(o.eta,' s')} <small>estimated</small></h3><RouteChain route={o.route}/><div className="candidate-stats"><span>{o.distance} m</span><span>{o.reconfigured} controllers</span><span>Preview <ArrowRight size={14}/></span></div></button>):<div className="panel quiet-empty"><GitBranch size={22}/><p>Route alternatives appear when an incident triggers planning.</p></div>}</div><section className="panel spaced"><div className="panel-title">Successor verification <span className="tag">PER CONTROLLER</span></div><Readiness state={s}/></section></>;
 }
 if(tab==='incidents'){
  const incidents=s.incidents||[],visible=filter==='ALL'?incidents:incidents.filter((i:any)=>i.status===filter);
  return <><div className="incident-overview"><div><span className="eyebrow">INCIDENT OPERATIONS</span><h2>{active.length?`${active.length} active disruption${active.length===1?'':'s'}`:'The corridor is clear.'}</h2><p>Track every activation, resolution and recovery decision.</p></div><button className="button danger" disabled={disabled} onClick={onAdd}><Zap size={16}/> Incident control</button></div><div className="operation-grid"><section className="panel"><div className="panel-title">Impact on the network <span className="tag">3D SIMULATION</span></div><SceneView {...common} compact/></section><section className="panel"><div className="panel-title">Incident register <span className="tag">{incidents.length}</span></div><div className="segmented" aria-label="Filter incidents">{['ALL','ACTIVE','SCHEDULED','RESOLVED'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f.toLowerCase()}</button>)}</div><div className="incident-register">{visible.length?[...visible].reverse().map((i:any)=><article key={i.id}><span className={`incident-symbol ${i.status==='ACTIVE'?'active':''}`}><TriangleAlert size={19}/></span><div><b>{i.kind} · {i.controller||i.edge?.join(' → ')}</b><p>{i.status} · {i.trigger==='approach'?`${i.distance} m before ${i.junction}`:i.activated_at!=null?`${i.activated_at}s`:`at ${i.at}s`}</p></div>{['ACTIVE','SCHEDULED'].includes(i.status)&&<button className="button small secondary" disabled={disabled} onClick={()=>action(`/incidents/${i.id}/resolve`)}>{i.status==='ACTIVE'?'Resolve':'Cancel'}</button>}</article>):<div className="quiet-empty"><ShieldCheck size={20}/><p>No {filter==='ALL'?'recorded':filter.toLowerCase()} incidents.</p></div>}</div></section></div><IncidentPanel state={s} disabled={disabled} action={action} onAdd={onAdd}/></>;
 }
 if(tab==='controllers'){
  const c=s.controllers.find((v:any)=>v.id===selected)||s.controllers[0];
  return <><div className="controller-grid">{s.controllers.map((v:any)=><button className={`controller-card ${v.id===selected?'selected':''}`} key={v.id} onClick={()=>onSelect(v.id)}><div><span className="controller-id">{v.id}</span><span className={`signal-orb ${v.phase.toLowerCase()}`}/></div><h3>{!v.online?'Disconnected':!v.readback||!v.writable?'Capability missing':v.mode}</h3><p>{v.profile}</p><div className="controller-meta"><span>E{v.generation}</span><span>{v.evidence_age} s evidence age</span></div><div className="controller-health"><i className={v.online?'ok':''}/><i className={v.readback?'ok':''}/><i className={v.writable?'ok':''}/></div></button>)}</div><div className="operation-grid spaced"><section className="panel"><div className="panel-title">Selected junction · {c.id}</div><SceneView {...common} compact/></section><section className="panel panel-pad"><span className="eyebrow">LOCAL EVIDENCE · {c.id}</span><h2>{c.last_reason}</h2><Facts items={[["Signal phase",c.phase],['Readback',c.readback?'Available':'Unavailable'],['Write authority',c.writable?'Available':'Unavailable'],['Evidence age',`${c.evidence_age} s`],['Rejected commands',c.rejected],['Local generation',`E${c.generation}`]]}/><button className="button secondary full" disabled={disabled||!active.some((i:any)=>i.controller===c.id)} onClick={()=>action(`/controllers/${c.id}/restore`)}>Restore {c.id}</button><details className="evidence-details"><summary>Inspect prepared and committed evidence</summary><pre>{JSON.stringify({prepared:c.prepared,committed:c.committed_state},null,2)}</pre></details></section></div></>;
 }
 if(tab==='hospitals')return <><section className="destination-hero"><div className="hospital-icon"><Hospital size={40}/></div><div><span className="eyebrow">SIMULATED DESTINATION</span><h2>Central Hospital</h2><p>Arrival is modeled. Clinical acceptance is a separate confirmation.</p></div><span className="status-tag neutral">NOT CONNECTED</span></section><div className="operation-grid"><section className="panel"><div className="panel-title">Destination approach <MapPin size={16}/></div><SceneView {...common}/></section><section className="panel panel-pad"><span className="eyebrow">DESTINATION COORDINATION</span><h2>Visibility without assumptions.</h2><Facts items={[["Emergency acceptance",'Unknown'],['Available beds','Not supplied'],['Clinical capabilities','Not supplied'],['Last confirmed update','No hospital integration'],['Simulation arrival',s.status==='COMPLETE'?'Reached destination':'Not yet arrived']]}/><div className="notice-box"><Hospital size={22}/><p>This hospital is part of the simulation. A map marker or estimated arrival time does not confirm admission or clinical suitability.</p></div><button className="button secondary full" onClick={()=>onNavigate('missions')}>Return to mission <ArrowRight size={15}/></button></section></div></>;
 const m=s.metrics||{},history=s.recovery_history||[],maxDuration=Math.max(1,...history.map((h:any)=>(h.ended??s.time)-h.started));
 return <><div className="analytics-grid">{[['Journey elapsed',value(s.time,' s'),Clock],['Completed transfers',m.recovery_count||0,GitBranch],['Stale commands blocked',m.stale_rejected||0,ShieldCheck],['Fallback entries',m.fallbacks||0,TriangleAlert]].map(([label,n,Icon]:any)=><article className="analytics-stat" key={label}><span><Icon size={20}/>{label}</span><strong>{n}</strong><small>Current recorded simulation</small></article>)}</div><div className="operation-grid"><section className="panel"><div className="panel-title">Recovery duration by generation <span className="tag">SIMULATED SECONDS</span></div><div className="recovery-chart">{history.length?history.map((h:any)=><div key={h.generation}><span>E{h.generation}</span><div className="chart-track"><div style={{width:`${((h.ended??s.time)-h.started)/maxDuration*100}%`}} className={h.stage==='COMMITTED'?'committed':''}/></div><b>{value((h.ended??s.time)-h.started,' s')}</b><small>{h.stage}</small></div>):<div className="quiet-empty"><GitBranch size={24}/><p>Complete a recovery to populate this chart.</p></div>}</div></section><section className="panel panel-pad"><span className="eyebrow">EVALUATION SUMMARY</span><h2>Measured, not assumed.</h2><Facts items={[["Total reconfiguration work",m.reconfigured_total||0],['Committed recovery time',value(m.total_recovery_seconds,' s')],['Reported SUMO collisions',s.collisions??'Not reported by this engine'],['Stale commands accepted',m.unsafe_acceptances||0],['Travel-time improvement','Requires matched comparison']]}/><button className="button primary full" onClick={()=>onNavigate('experiments')}>Run a controlled comparison <ArrowRight size={15}/></button></section></div><section className="panel spaced"><div className="panel-title">Evidence timeline <Activity size={16}/></div><EventTimeline events={s.events||[]}/></section></>;
}
